### CREATE five documents.
POST http://localhost:3000/blogs HTTP/1.1
content-type: application/json

{
    "blogTitle": "Hello",
    "blogText": "This is a test"
}


### CREATE 2
POST http://localhost:3000/blogs HTTP/1.1
content-type: application/json

{
    "blogTitle": "Hello again",
    "blogText": "This is a also a test"
}

### CREATE 3
POST http://localhost:3000/blogs HTTP/1.1
content-type: application/json

{
    "blogTitle": "Once more",
    "blogText": "This is a test, too"
}

### CREATE 4
POST http://localhost:3000/blogs HTTP/1.1
content-type: application/json

{
    "blogTitle": "No. 4 here",
    "blogText": "Again, here is a test 123"
}

### CREATE 5
POST http://localhost:3000/blogs HTTP/1.1
content-type: application/json

{
    "blogTitle": "Last test is the charm",
    "blogText": "This is another test"
}


### RETRIEVE all documents.
GET http://localhost:3000/blogs HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/blogs/65fc736d9277020b386ed504 HTTP/1.1


### UPDATE one document, by ID.
### Replace the ID in the following request with one that exists
### and update the year:
PUT http://localhost:3000/blogs/65fc73729277020b386ed508 HTTP/1.1
content-type: application/json

{
   "blogTitle": "No. 4 here",
    "blogText": "Again, here is a test 123123"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/blogs/65fc73709277020b386ed506 HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/blogs HTTP/1.1

